### ISSUE TITLE
geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by k1ngpr4wn** [bmdyy/tudo#4]
The admin interaction simulation wasn't working for me.

In the container I had to modify /usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/service.py by commenting out:

```
# Set a port for CDP
# self.service_args.append("--websocket-port")
# self.service_args.append("%d" % utils.free_port())
```

And change /app/emulate_admin.py:

```
driver = webdriver.Firefox(firefox_options=opts)
```

to

```
driver = webdriver.Firefox(options=opts)
```

Seems there's some kind of version conflict but I didn't look into it too closely.

**Comment by dutragustavo** [comment]
It was probably caused because Selenium latest is now 4.0, an alternative fix to this is probably fixing the selenium version on Dockerfile changing the command to: 

```
RUN pip3 install selenium==3.141.0
``` 
I had this issue on [testr](https://github.com/bmdyy/testr).
